### ISSUE TITLE
Validate results from each evaluation

### ISSUE THREAD

**Issue by samestep** [gradbench/gradbench#98]
Currently, CI just builds the evals and tools and then runs all pairs. There is no signal about whether a tool succeeded or failed on a given eval. We want to designate a specific tool as the "golden" reference implementation (the plan is to use PyTorch), and then for each eval, define a way to compare the results of two tools on that eval. This also relates to #97, since we'll want to visualize those validation outputs on the website. Beyond this, we probably also want each eval to define how two runs should be visualized in more detail, beyond just a binary "correct/incorrect" decision.

**Comment by athas** [comment]
Validation needs to be part of an eval, since as far I understand it, `run.py` is just a very generic message broker, that doesn't actually understand anything about the messages it transmits.

**Comment by athas** [comment]
On the other hand, all an eval can do is send messages to the tool, so how is it supposed to report validation errors?

**Comment by samestep** [comment]
@athas `run.py` can (and I think probably should) validate the protocol itself, but the eval needs to describe how to validate the data it got from the session.

One way to do this could be to add an "end" message to the protocol, so when the eval wants to terminate the session (either successfully or unsuccessfully), it can send a message that `run.py` doesn't forward to the tool and instead just logs and exits. The eval could accumulate whatever it wants from the session into rich metadata in this final message, and the protocol could define some standard fields to be visualized consistently on the website (e.g. success vs failure, overall performance, etc).

**Comment by athas** [comment]
I have also come to the conclusion that making `run.py` somewhat protocol-aware is necessary. I think this is fine as GradBench is not supposed to be a completely generic testing tool. The most important thing is to make it easy to add new tools, and achievable to add new evals.

I don't think having an "end" message is a problem, but I don't think it's how to do validation. Now I'm considering a design where `evaluate` messages must have two fields that are known to `run.py`:

1. `name`, which is a human-readable string unique to the particular input.
2. `input`, which contains the actual input to the evaluation (currently a JSON object, may become a filename as per #99).

The response must then contain another field known to `run.py`:

1. `output`, which contains the result.

(You will not that `input`/`output` are actually the fields already used by GradBench.)

This means that `run.py` will have enough information to create a directory tree that contains the input and output for every evaluation. (And also the runtimes and such.) Validation can then be done *offline*. I propose a separate program per eval, e.g., `evals/hello/validate.py`. This also doesn't have to run within Docker, as presumably validation does not need any fancy code (because it has to be trustworthy). It is of course easy to write some glue code that runs evaluation automatically after benchmarking.

**Comment by athas** [comment]
The tool must also respond with the tool name, I realise.

**Comment by athas** [comment]
Working on this in #101.

**Comment by samestep** [comment]
Resolved by #101.
