### ISSUE TITLE
Support file sharing between evaluations and tools

### ISSUE THREAD

**Issue by samestep** [gradbench/gradbench#99]
Currently the only way to pass data between an eval and a tool is via JSON through the protocol. This becomes a bit unwieldy for evals that need to send a lot of input data or that require the tool to send back a lot of output data. Perhaps we should also allow a session to include a shared directory that the eval and tool can both and read and write.

This raises a couple questions:

1. How can the protocol (currently encapsulated in `run.py`) expose this in a way that remains agnostic of the way the eval and tool are implemented? Currently the eval and tool just need to be commands that can be run to produce processes with stdin and stdout, but this change would require them to have more complex interactions with the outside world. It might be fine though; we already have `eval.sh` and `tool.sh` pass the `--interactive` flag to `docker run`, so maybe we can just do a similar thing for a filesystem mount.
2. Should filesystem events be reflected in the protocol at all? Or should it simply be conventional? For instance, perhaps the eval can make sure to write an input file before it sends an `"evaluate"` command, and require that the tool write its output file before it sends its response.
3. How should output files be saved for later analysis and validation? Currently the entire session can be saved as one JSON file, but with this change, the filesystem could potentially undergo destructive writes in the course of a session. Should we just save all the files in the final state of the shared directory? Or should we impose some limitations that ensure that, e.g., files can only be written once and not overwritten?

**Comment by athas** [comment]
I have an idea for how to do this. If the protocol is modified such that the input and output data is represented as file names in the messages, then the `tool.sh` automation (or something it invokes) can automatically detect when a Docker image is invoked, and transparently copy files and and forth and rewrite the file names in the messages. This means the automation needs to be somewhat protocol-aware rather than just a dumb proxy, but the important thing is that specific tool implementations don't have to care - it will all be completely transparent.

I think persistent storage of output (and input) files should be done on the "host", understood as the system that runs `run.py`, outside the Docker images. Actual validation can be done in Docker images, by sending files there, using the same idea of transparently copying files and rewriting file names.

**Comment by samestep** [comment]
@athas this roughly lines up with what I was thinking, and I like the idea of handling it in `tool.sh`. How difficult would it be to throw together a prototype? If it's not too hard, I think I'd have an easier time deciding whether this makes sense upon looking at an initial implementation of the idea.

**Comment by athas** [comment]
I'm not much of a Docker expert, but I'll give it a shot.

**Comment by samestep** [comment]
As of #130, we've now ported all the evals from [ADBench](https://github.com/microsoft/ADBench) without needing this feature, so I'm going to close this; if we turn out to need it later, we can reopen it then.

**Comment by athas** [comment]
The reason this has not become necessary is because the PyTorch implementation (used for validation) is so slow that all the ADBench-derived evals use only the smallest datasets by default. It may still be the case that shuffling a 1GiB Jacobian over JSON is fine, but we should probably check at some point. Although I suspect the bottleneck will actually be the terminal printing in `run.py`.

**Comment by samestep** [comment]
Yep, so maybe e.g. #137 will help. As an aside, I've also considered changing the format printed by `run.py` from just JSON to [JSON Lines](https://jsonlines.org/), which would then make it easier to build something like `run-pretty.py` _on top of_ the intermediary rather than just replacing the entire intermediary.
